[package]
name = "keyboard-overlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.24.0"

[build-dependencies]
bindgen = "0.69.1"
